{% set version = GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH %}

package:
  name: pyemma-doc
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ version }}
source:
  path: ../..

requirements:
  build:
    # there is a bug in conda-build 3.10.9 which does not allow our version number...
    - pyemma-dev #=={{ version }}
    - mdshare
    - nbconvert
    - sphinx
    - ipython
    - ipywidgets
    - sphinx_rtd_theme

build:
  noarch: generic
  script_env:
  # options for sphinx builder
    - SPHINXOPTS
  # options for notebook conversion (jupyter nbconvert)
    - nbflags
  # cfg dir
    - PYEMMA_CFG_DIR
